[tool.poetry]
name = "vaporwave-merch-tracker"
version = "0.1.0"
description = ""
authors = ["idleherb"]
license = "unlicense"

[tool.poetry.dependencies]
python = "^3.10"
parsel = "^1.6.0"
aiohttp = "^3.8.1"
dataclasses-json = "^0.5.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
mypy = "^1.2"
flake8 = "^5.0.4"
pytest-cov = "^3.0.0"
pytest-aiohttp = "^1.0.4"
pytest-unordered = "^0.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
